app_cc/urls.py
from django.urls import path
from . import views

app_name = 'app_cc'

urlpatterns = [
    path('index/', views.index, name="index"),
    path('listado/', views.lista_colaborador, name="lista_colaborador"),
    path('',views.login,name='login'),
  	path('salir',views.cerrar_sesion,name='cerrar_sesion'),
 	path('registrar/colaborador/',views.registrar_colaborador,name='registrar_colaborador'),
 	path('eliminar/colaborador/<int:id_colaborador>/',views.eliminar_colaborador,name='eliminar_colaborador'),
 	path('modificar/colaborador/<int:id_colaborador>/',views.modificar_colaborador,name='modificar_colaborador'),

]

proyectocc/urls.py
from django.contrib import admin
from django.urls import path, include
from app_cc import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name='login'),
    path('principal/', include('app_cc.urls')),
    #path('', app_cc.views.index, name="index"),

]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

app_cc/models.py
from django.db import models

# Create your models here.

class Genero(models.Model):
	descripcion_genero = models.CharField(max_length=100)

	def __str__(self):
		return "{}-{}".format(self.pk,self.descripcion_genero)


class Colaborador(models.Model):
	identificacion = models.CharField(max_length=20)
	nombres = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=50)
	telefono = models.CharField(max_length=20)
	fecha_nacimiento = models.DateField(auto_now_add=False)
	Genero =  models.ForeignKey(Genero, on_delete=models.CASCADE)
	

	def __str__(self):
		return "{}-{} {}".format(self.identificacion,self.nombres,self.telefono)

app_cc/views.py
from django.shortcuts import render
import cx_Oracle
from django.db import transaction,connections
from datetime import datetime
from django.http import HttpResponseRedirect,JsonResponse,HttpResponse
from django.contrib.auth import login as auth_login,logout,authenticate
from django.urls import reverse
from django.shortcuts import render,redirect
from app_cc.models import *

# Create your views here.
def login(request):
	mensaje = ''
	if request.user.is_authenticated:
		return HttpResponseRedirect(reverse('app_cc:lista_colaborador'))
	
	if request.method == 'POST':
		username = request.POST.get('usuario')
		contrasenia = request.POST.get('contrasenia')
		user = authenticate(username=username,password=contrasenia)
		if user is not None:
			if user.is_active:
				auth_login(request,user)
				return redirect('app_cc:lista_colaborador')
			else:
				mensaje = 'USUARIO INACTIVO'
				return render(request,'login.html',{'mensaje':mensaje})
		else:
			mensaje = 'USUARIO O CONTRASEÑA INCORRECTA'
			return render(request,'login.html',{'mensaje':mensaje})
	return render(request,'login.html',{'mensaje':mensaje})

def cerrar_sesion(request):
	logout(request)
	return HttpResponseRedirect(reverse('app_cc:login'))


def index(request):
	consulta = Colaborador.objects.all()
	generos = Genero.objects.all()
	data = {'lista_colaborador':consulta,'generos':generos}
	return render(request, "index.html",data)
#    try:
#        conexion=cx_Oracle.connect("jaguaroracle", "Jaguar2021", "173.249.59.89:1521/xe")
#    except Exception as error:
#        print ("nel .Error: "+error)
#    else: 
#        print("Si!!!!")

def lista_colaborador(request):
	consulta = Colaborador.objects.all()
	generos = Genero.objects.all()
	data = {'lista_colaborador':consulta,'generos':generos}
	return render(request,'index.html',data)


def registrar_colaborador(request):
	guardar_editar = True
	generos = Genero.objects.all()
	ret_data,query_colaborador,errores = {},{},{}

	if request.method == 'POST':
		print("ESTAMOS EN EL METODO POST")
		ret_data['identificacion'] = request.POST.get('identificacion')
		ret_data['nombres'] = request.POST.get('nombres')
		ret_data['apellidos'] = request.POST.get('apellidos')
		ret_data['telefono'] = request.POST.get('telefono')
		ret_data['fecha_nacimiento'] = request.POST.get('fecha_nacimiento')
		ret_data['genero'] = int(request.POST.get('genero'))
		if request.POST.get('identificacion') == '':
			errores['identificacion'] = "DEBES INGRESAR LA IDENTIDAD"
		else:
			query_colaborador['identificacion'] = request.POST.get('identificacion')
		
		if request.POST.get('nombres') == '':
			errores['nombres'] = "DEBES INGRESAR NOMBRES"
		else:
			query_colaborador['nombres'] = request.POST.get('nombres')

		query_colaborador['apellidos'] = request.POST.get('apellidos')
		query_colaborador['telefono'] = request.POST.get('telefono')
		query_colaborador['fecha_nacimiento'] = request.POST.get('fecha_nacimiento')
		query_colaborador['Genero'] = Genero.objects.get(pk=request.POST.get('genero'))

		if not errores:
			try:
				colaborador = Colaborador(**query_colaborador)
				colaborador.save()
			except Exception as e:
				transaction.rollback()
				print (e)
				errores['administrador'] =  e
				ctx = {'generos':generos,
						'errores':errores,
						'ret_data':ret_data,
						'guardar_editar':guardar_editar}
				return render(request,'registrar_colaborador.html',ctx)
			else:
				transaction.commit()
				return HttpResponseRedirect(reverse('app_cc:lista_colaborador'))
		else:
			ctx = {'generos':generos,
					'errores':errores,
					'ret_data':ret_data,
					'guardar_editar':guardar_editar}
			return render(request,'registrar_colaborador.html',ctx)
	else:
		print("ESTAMOS EN EL METODO GET")
		ctx = {'generos':generos,'guardar_editar':guardar_editar}
		return render(request,'registrar_colaborador.html',ctx)

def eliminar_colaborador(request,id_colaborador):
	eliminar = Colaborador.objects.get(pk=id_colaborador).delete()
	return HttpResponseRedirect(reverse('app_cc:lista_colaborador'))

def modificar_colaborador(request,id_colaborador):
	consulta = Colaborador.objects.all()
	generos = Genero.objects.all()
	guardar_editar = False
	colaborador = Colaborador.objects.get(pk=id_colaborador)
	ret_data,query_colaborador,errores = {},{},{}

	if request.method=='POST':
		print("aqui va modificar")

		if request.POST.get('identificacion') == '' or request.POST.get('nombres') == '' or request.POST.get('apellidos') == '' or request.POST.get('telefono') == '' or request.POST.get('fecha_nacimiento') == '' or int(request.POST.get('genero')) == 0:
			errores['identificacion'] = "HAY ERRORES"

		if not errores:
			
			try:
				colaborador = Colaborador.objects.filter(pk=id_colaborador).update(identificacion=request.POST.get('identificacion'),
																					nombres=request.POST.get('nombres'),
																					apellidos=request.POST.get('apellidos'),
																					telefono=request.POST.get('telefono'),
																					fecha_nacimiento=request.POST.get('fecha_nacimiento'),
																					Genero=request.POST.get('genero')
																				)

			except Exception as e:
				print(e )
				return HttpResponseRedirect(reverse('app_cc:lista_colaborador')+"?error")
			else:
				return HttpResponseRedirect(reverse('app_cc:lista_colaborador'))
		else:
			return HttpResponseRedirect(reverse('app_cc:lista_colaborador')+"?error")
	else:
		return HttpResponseRedirect(reverse('app_cc:lista_colaborador'))

app_cc/templates/index.html
{% extends "base.html" %}
{% block title %}
    UTH | COLABORADOR
{% endblock title %}
{% load static %}
{% block content %}
	<section class="content">
		<div class="container-fluid">
			<table id="tabla_colaborador" class="table table-striped table-bordered" style="width:100" >
				<thead>
					<tr>
						<th>Identificacion</th>
						<th>Nombres</th>
						<th>Apellidos</th>
						<th>Teléfono</th>
						<th>Fecha Nac.</th>
						<th>Genero</th>
						<th>Eliminar</th>
						<th>Modificar</th>
					</tr>
				</thead>
				<tbody>
					{% for colaborador in lista_colaborador %}
						<tr>
							<td>{{colaborador.identificacion}}</td>
							<td>{{colaborador.nombres}}</td>
							<td>{{colaborador.apellidos}}</td>
							<td>{{colaborador.telefono}}</td>
							<td>{{colaborador.fecha_nacimiento}}</td>
							<td>{{colaborador.Genero}}</td>
							<td>
								<center>
									<a href="{% url 'app_cc:eliminar_colaborador' colaborador.pk  %}" class="btn btn-block btn-danger" onclick="return confirm('Esta seguro de eliminar el registro')">ELIMINAR</a>
								</center>
							</td>

							<td>
								<center>
									{# <a href="{% url 'app_cc:modificar_colaborador' colaborador.pk  %}" class="btn btn-block btn-primary" onclick="return confirm('Esta seguro de modificar el registro')">MODIFICAR</a> #}

									<button type="button" class="btn btn-primary " data-toggle="modal" data-target="#modal{{colaborador.pk}}">
					                  MODIFICAR
					                </button>

					                <div class="modal fade" id="modal{{colaborador.pk}}">
								        <div class="modal-dialog">
								          <div class="modal-content">
								            <div class="modal-header">
								              <h4 class="modal-title">{{colaborador.nombres}} {{colaborador.apellidos}}</h4>
								              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
								                <span aria-hidden="true">&times;</span>
								              </button>
								            </div>
								            <div class="modal-body">
								            
								            <form role="form" method="post" action="{% url 'app_cc:modificar_colaborador' colaborador.pk %}">
								              {% csrf_token %}
								              <div class="row">
						                  		<div class="col-sm-6">
							                		<div class="form-group">
									            	    <label for="exampleInputEmail1">Identificación<span style="color:red">*</span></label>
									                    <input type="text" class="form-control" id="id_identificacion"
									                    name="identificacion" placeholder="Identificación" value="{{colaborador.identificacion}}" required="">
								                  	</div>
								                </div>
								                <div class="col-sm-6">
								                  	<div class="form-group">
									                    <label for="exampleInputEmail1">Nombres<span style="color:red">*</span></label>
									                    <input type="text" class="form-control" id="id_nombres" name="nombres" placeholder="Nombres" value="{{colaborador.nombres}}" required>
								                  	</div>
								                </div>
						                  	  </div>

							                  	<div class="row">
							                  		<div class="col-sm-6">
									                  	<div class="form-group">
										                    <label for="exampleInputEmail1">Apellidos<span style="color:red">*</span></label>
										                    <input type="text" class="form-control" id="id_apellidos" name="apellidos" placeholder="Apellidos" value="{{colaborador.apellidos}}" required>
								                  		</div>
							                  		</div>
							                  		<div class="col-sm-6">
						                  				<div class="form-group">
										                    <label for="exampleInputEmail1">Teléfono<span style="color:red">*</span></label>
										                    <input type="text" class="form-control" id="id_telefono" name="telefono" placeholder="Teléfono" value="{{colaborador.telefono}}" required>
								                  		</div>
						                  			</div>
						                  	    </div>

						                  		<div class="row">
						                  			<div class="col-sm-6">
								                		<div class="form-group">
										                  	<label>Fecha de nacimiento<span style="color:red">*</span></label>
											                  <div class="input-group">
											                    <div class="input-group-prepend">
											                      <span class="input-group-text">
											                        <i class="far fa-calendar-alt"></i>
											                      </span>
											                    </div>
											                    <input type="text" class="form-control float-right" id="id_fecha_nacimiento" name="fecha_nacimiento" value="{{colaborador.fecha_nacimiento|date:'Y-m-d'}}" required>
										                  	   </div>
										           		</div>
									           		</div>

								                	<div class="col-sm-6">
								                		<div class="form-group">
								                          <label>Genero<span style="color:red">*</span></label>
								                          <select class="form-control selectpicker" style="width: 100%;" id="id_genero" data-live-search="true" name="genero">
								                              <option value='0' selected="selected" >--SELECCIONE--</option>
								                             {% for genero in generos  %}
								                                {% ifequal genero.pk  colaborador.Genero.pk   %} 
								                                  <option value='{{genero.pk}}' selected>{{genero.descripcion_genero}}</option>
								                                {% else %}
								                                    <option value='{{genero.pk}}'>{{genero.descripcion_genero}}</option>
								                                {% endifequal %}
								                             {% endfor %}
								                            </select>
								                    	</div>
								                	</div>
						                  		</div> 
								            </div>
								            <div class="modal-footer justify-content-between">
								              <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
								              <button type="submit" class="btn btn-primary">Guardar</button>
								            </div>

								         	</form>
								          </div>
								          <!-- /.modal-content -->
								        </div>
								        <!-- /.modal-dialog -->
								      </div>
								      <!-- /.modal -->
								</center>
							</td>
						</tr>	
					{% endfor %}
				</tbody>
			</table>
			
		</div>
	</section>
{% endblock content %}

{% block js %}
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#tabla_colaborador').DataTable();
		});
		
		/*variable python
		{% if error %}
			alert("EXISTE UN ERROR AL MODIFICAR");	
		{% endif %}*/

		{% if  'error' in request.GET %}
			alertify.alert("DEBE INGRESAR TODOS LOS CAMPOS OBLIGATORIOS O DEBES SELECCIONAR UN GENERO",function(){
				history.pushState(null,"","{% url 'app_cc:lista_colaborador' %}");
			});
		{% endif %}

		//alertify.alert("holaaaa");
	</script> 
{% endblock js %}

app_cc/templates/login.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% static 'index2.html"><b>Inicio</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Iniciar Sesión</p>

      <form action="{% url 'app_cc:login' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Usuario" id="id_usuario" name="usuario">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Contraseña" id="id_contrasenia" name="contrasenia">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Iniciar</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div>
      <!-- /.social-auth-links -->

      <!--<p class="mb-1">
        <a href="forgot-password.html">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="register.html" class="text-center">Register a new membership</a>
      </p>
    </div>-->
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

</body>
</html>

app_cc/templates/login1.html


<!DOCTYPE html>
<html>
<head>
	<title>UTH | INICIO DE SESION</title>
   <!--Made with love by Mutiullah Samim -->
     {% load static %}
 <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'login_uth/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'login_uth/login.css' %}">
  <script src="{% static 'login_uth/bootstrap.min.js' %}"></script>
  <script src="{% static 'login_uth/jquery.min.js' %}"></script>
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">

				<form method="post" action="{% url 'app_cc:login' %}">
					{% csrf_token %}
					<div>ERROR{{mensaje}}</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username" id="id_usuario" name="usuario">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password" id="id_contrasenia" name="contrasenia">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="#">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app_cc/templates/registrar_colaborador.html
{% extends "base.html" %}
{% block title %}
REGISTRO
{% endblock title %}
{% load static %}
{% block content %}
    <section class="content">
		<div class="container-fluid">
			<div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">
          {% if guardar_editar %}
            REGISTRAR
          {% else %}
            MODIFICAR
          {% endif %} COLABORADOR</h3>
        </div>
        {% if guardar_editar %}
          <form role="form" method="post" action="{% url 'app_cc:registrar_colaborador' %}" >
        {% else %}
          <form role="form" method="post" action="{% url 'app_cc:modificar_colaborador' id_colaborador %}" >    
        
        {% endif %}
       
          {% csrf_token %}
          {% if errores.administrador %}
            <div class="alert alert-danger alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-ban"></i> ERROR!{{errores.administrador}}</h5>
            </div>
          {% endif %}
          <div class="card-body">
          <div class="row">
          	<div class="col-sm-4">
        		  <div class="form-group">
                <label for="exampleInputEmail1">Identificación</label>
                <input type="text" class="form-control" id="id_identificacion"
                name="identificacion" placeholder="Identificación" value="{{ret_data.identificacion}}">
            	</div>
                
              {% if errores.identificacion %}
                <div class="alert alert-danger alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <h5><i class="icon fas fa-ban"></i> ERROR!{{errores.identificacion}}</h5>
                </div>
              {% endif %}
          	</div>

          	<div class="col-sm-4">
      		 	  <div class="form-group">
                  <label for="exampleInputEmail1">Nombres</label>
                  <input type="text" class="form-control" id="id_nombres" name="nombres" placeholder="Nombres" value="{{ret_data.nombres}}">
              	</div>

                {% if errores.nombres %}
                  <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-ban"></i> ERROR!{{errores.nombres}}</h5>
                  </div>
                {% endif %}
          	</div>

          	<div class="col-sm-4">
          		<div class="form-group">
                  <label for="exampleInputEmail1">Apellidos</label>
                  <input type="text" class="form-control" id="id_apellidos" name="apellidos" placeholder="Apellidos" value="{{ret_data.apellidos}}">
            		</div>
          	</div>

          </div>
            
          <div class="row">
          	<div class="col-sm-4">
          		<div class="form-group">
                  <label for="exampleInputEmail1">Teléfono</label>
                  <input type="text" class="form-control" id="id_telefono" name="telefono" placeholder="Teléfono" value="{{ret_data.telefono}}">
            		</div>
          	</div>

            <div class="col-sm-4">
              <div class="form-group">
                  <label>Fecha de nacimiento</label>
                  <div class="input-group" >
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="far fa-calendar-alt"></i>
                      </span>
                    </div>
                    <input type="text" class="form-control float-right" id="id_fecha_nacimiento" name="fecha_nacimiento" value="{{ret_data.fecha_nacimiento|date:'YYYY-MM-DD'}}" >
                </div>
             </div>
            </div>
            <div class="col-sm-4">
              <div class="form-group">
                <label>Genero</label>
                <select class="form-control selectpicker" style="width: 100%;" id="id_genero" data-live-search="true" name="genero">
                    <option value='0' selected="selected" >--SELECCIONE--</option>
                   {% for genero in generos  %}
                      {% ifequal genero.pk  ret_data.pk_genero   %} 
                        <option value='{{genero.pk}}' selected>{{genero.descripcion_genero}}</option>
                      {% else %}
                          <option value='{{genero.pk}}'>{{genero.descripcion_genero}}</option>
                      {% endifequal %}
                     
                   {% endfor %}
                  </select>
              </div>
            </div>
          </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">GUARDAR</button>
          </div>
        </form>
      </div>
		</div>
	</section>
{% endblock content %}	
{% block js %}
	    <script type="text/javascript">
	    	$('#id_fecha_nacimiento').daterangepicker({
          
			    singleDatePicker: true,
			    showDropdowns: true,
			    minYear: 1901,
			    maxYear: parseInt(moment().format('YYYY'),10),
          locale: {
            format: 'YYYY-MM-DD',
           
          }
			  });

	    	 $('#id_genero').selectpicker({
              noneResultsText: 'No hay datos'
          });
	    </script>
{% endblock js %}	